Create utils-columns.R
IntegralEnvision/integral pull request #16
Opened 2022-05-23 16:58 UTC by ebenp

Added A function to get the column number from an Upper or lower case letter.

- [x]  checked against latest main branch

- [x] documented following package documentation
- [x] checked lower and upper case cases

2022-05-25 19:32 UTC, jzadra requested changes
I'd suggest adding some basic error handling if the input isn't a single character or a vector of single characters.

For instance:

```
> letnum("ab")
integer(0)
> letnum(c("ab", "c"))
[1] 3
```

If this is used interactively, it's a bit more obvious what's happening.  But if it were in a mutate() you would get weird results without realizing it.

perhaps check:
```
> test <- c("ab", "c", "5")
> all(test %in% letters | test %in% LETTERS)
[1] FALSE
```
This returns `FALSE` if one of the values has more than one character, and if one of the values is numeric stored as character.

You could either use stop("your error message") or return(cli::cli_alert_danger("Error in letnum(): values must be single letters") or something along those lines.

2022-05-25 20:13 UTC, ebenp commented
Thanks. I added some warning code. I think this is a good addition.

2022-05-25 21:37 UTC, jzadra requested changes

2022-05-25 21:37 UTC, jzadra commented on R/utils-columns.R
> +  if (any(nchar(x) > 1, length(x) > 1, x == "")) {
This will return FALSE if x is a number stored as numeric or a number stored as character.  I'd suggest perhaps:
```
if(length(x) > 1 || to_upper(x) %ni% LETTERS) 
```
Because it the %ni% will return TRUE for numerics, numbers stored as characters, and multiple characters.

2022-05-25 21:37 UTC, jzadra commented on R/utils-columns.R
> +  if (any(nchar(x) > 1, length(x) > 1, x == "")) {
And also the help message should indicate that it can't be a vector (ie remove the plural and state that).  Are you sure that you don't want it to handle vectors > length 1?

2022-05-26 15:12 UTC, ebenp commented
@jzadra  Updated for 2 and 3 letter combinations, error checking and to allow vectors.
Tests I ran included: 
```
letnum("A")
letnum("Aa")
letnum("Aaz")
letnum(1)
letnum("1")
letnum(c("AA", 1, 23))
```

2022-05-26 16:00 UTC, jzadra approved these changes

2022-05-26 16:03 UTC, merged